### ISSUE TITLE
Testing with SNS/SQS using Localstack - mapping directory

### ISSUE THREAD

**Issue by datasmithadvtech** [joerg-pfruender/joerg-pfruender.github.io#3]
hi. read your article

How do you map a directory into /docker-entrypoint-initaws.d of the localstack’s docker-container volume?

**Comment by joerg-pfruender** [comment]
Hi @datasmithadvtech ,

thank you for your message!
If you use the localstack docker container, then you can use the `withFileSystemBind` method, see 
https://www.testcontainers.org/features/files/

If you use a docker-compose container, then you can use the docker-compose.yml file to specify the volumes: https://docs.docker.com/compose/compose-file/compose-file-v3/#volume-configuration-reference

I'd recommend to understand docker's concept of volumes in case of any error messages.

Good luck!

Jörg
